### PR TITLE
Added optional loading of data from ~/.config/dotmanager

### PR DESCRIPTION
**Pull request by AGitBoy**
This automatically checks for the existence of the directory `~/.config/dotmanger`. If it exists it loads configs from this directory rather than `data/`.  

This is beneficial as the code is not entirely dependent on where the executable is being run. However, the project at its current state cannot be run outside of the source folder, even with this commit, due to the way the project is set up and packaged. I would like this to be the first commit of a few to make the project installable on systems as a global executable.

On another note, I do plan to expand upon this code and load config files in `/etc/dotmanager` and `$HOME/.config/dotmanager`, merging the global system configs with the local user ones. However this requires quite a bit of work, and a rewrite of certain parts of the code, so I want your input on it first.

### CODE REVIEW

**Comment by RickestRickSanchez** [comment]
That's something I would like as well. Especially making the project installable and provide packages is one of the next major steps.

> On another note, I do plan to expand upon this code and load config files in /etc/dotmanager and $HOME/.config/dotmanager, merging the global system configs with the local user ones. However this requires quite a bit of work, and a rewrite of certain parts of the code

I already did some rewriting of `constants.py` to load a config file from any location. I needed this for the upcoming regression tests. Take a look at  [761e8c7](https://github.com/RickestRickSanchez/dotmanager/commit/761e8c717c7a747b32830ac0b8b3f15414d76f54) on the regression-tests branch. `loadconfig()` will already merge the config file with the fallback values. You can extend this function to first load a config from `/etc` and merge it with the config that was provided. If none was provided you would merge it with the config from `$HOME/.config/dotmanager`.
It will take some time until I'm finished with the regression tests so if you like to do this I can merge this single commit into the master.

Also the blacklist was never intended to be modified by the user. It should prevent that the user doesn't mess up their system accidentally.
Would you see a need to modify the blacklist? If not, this can stay in the `data` for now.

**Comment by AGitBoy** [comment]
If you merged that commit to master, I would extend the function to automatically load for you. I do believe it would be useful to add the blacklist to the user configuration.

-------- Original Message --------

**Comment by RickestRickSanchez** [comment]
> If you merged that commit to master, I would extend the function to automatically load for you.

Here you go!

>  I do believe it would be useful to add the blacklist to the user configuration.

Alright then I would suggest to put this in `/etc` as well. But I think in this case the whitespaces of every line should be stripped, because patterns wouldn't match if the user accidentally adds trailing whitespace.

**Comment by AGitBoy** [comment]
I'll write the code when I get home :smile:

-------- Original Message --------

**Comment by AGitBoy** [comment]
I'll open a new one when I'm done

**Pull request closed without merging**
